# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0004_checkloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkloan',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
