# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0005_checkloan_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanentries',
            name='check_email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authusers',
            name='emailid',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loanentries',
            name='loan_limit',
            field=models.IntegerField(),
        ),
    ]
