# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0006_auto_20160906_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanentries',
            name='check_email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
